.TH SSLSNIFF 1
.SH NAME
sslsniff \- basic tool that analysing SSL traffic
.SH SYNOPSIS
.B sslsniff
[\fB\-r\fR <file>]
[\fB\-i\fR interface]
.SH DESCRIPTION
.B sslsniff
the tool analyses SSL traffic either realtime from a given interface or offline from given pcapng file
.SH OPTIONS
.TP
.BR \-n
Name of a pcapng file to be analyzed.
.TP
.BR \-i
Name of an interface on which the SSL sniffing should be done.
